branch: master
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'

gradle:
  node:
    detect: true # try to detect system node, if found skip download evaluation.
    download: false # download a node dist and use it, if it was not detected
    distUrl: https://nodejs.org/dist # dist download root url (default)
    packages: # extra packages needed in semantic-release plugins
      - '@semantic-release/commit-analyzer'
      - '@semantic-release/release-notes-generator'
      - '@semantic-release/github'