site_name: Gradle Semantic Release Plugin


nav:
  - Description: index.md
  - Configuration: configuration.md
#  - Flowchart: flow.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.8.4/mermaid.min.js

theme:
  name: material
  language: en
  include_search_page: false
  search_index_only: true
  icon:
    repo: fontawesome/brands/github
  repo_name: illjut/semrel
  repo_url: https://github.com/illjut/semrel


plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
