name: Branch build

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      run: gradle test build
      env:
        PUBLISH_USER: ${{ github.actor }}
        REGISTRY_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
